name: NER API demo application

# Run this workflow every time a new commit is pushed to the repository
on: push

jobs:
  build:
    name: Build and test app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Run backend tests
        run: docker-compose run backend make test
